export const QUOTES = [
  { text: 'Focus is the art of knowing what to ignore.', author: 'James Clear' },
  { text: 'The best way out is always through.', author: 'Robert Frost' },
  { text: 'Do one thing at a time, and do it well.', author: 'Steve Jobs' },
  { text: 'Success is the sum of small efforts repeated day in and day out.', author: 'Robert Collier' },
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', author: 'James Clear' },
  { text: 'Clarity precedes mastery.', author: 'Robin Sharma' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln' },
  { text: 'The ability to concentrate and to use time well is everything.', author: 'Lee Iacocca' },
  { text: 'Lost time is never found again.', author: 'Benjamin Franklin' },
  { text: 'Your mind is for having ideas, not holding them.', author: 'David Allen' },
  { text: 'Creativity is a wild mind and a disciplined eye.', author: 'Dorothy Parker' },
  { text: 'The only way around is through.', author: 'Robert Frost' },
  { text: 'Small steps every day add up to big results.', author: 'Unknown' },
  { text: 'The best focus happens when you have nothing to hide.', author: 'Nir Eyal' },
  { text: 'Don’t let what you cannot do interfere with what you can do.', author: 'John Wooden' },
  { text: 'Amateurs sit and wait for inspiration, the rest of us just get up and go to work.', author: 'Stephen King' },
  { text: 'Motivation gets you started. Habit keeps you going.', author: 'Jim Ryun' },
  { text: 'It always seems impossible until it’s done.', author: 'Nelson Mandela' },
  { text: 'If it’s not on your calendar, it’s not real.', author: 'Robin Sharma' },
];
